/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectinifinal;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josue
 */
public class TablaVehiculos extends javax.swing.JPanel {
private ArbolVehiculos arbolVehiculos;
    /**
     * Creates new form TablaVehiculos
     */
    public TablaVehiculos() {
        initComponents();
        this.arbolVehiculos = GestorDatosGlobal.getVehiculos();
        
    }

    
   public JPanel getTablaVehiculos(){
   return PanelHistorialMultas;
   }
   
 public void cargarInordenEnTabla(JTable tabla) {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0);
        recorrerInorden(arbolVehiculos.getRaiz(), modelo);
    }

    public void cargarPreordenEnTabla(JTable tabla) {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0);
        recorrerPreorden(arbolVehiculos.getRaiz(), modelo);
    }

    public void cargarPostordenEnTabla(JTable tabla) {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0);
        recorrerPostorden(arbolVehiculos.getRaiz(), modelo);
    }

    // RECORRIDOS DEL ÁRBOL
  
    private void recorrerInorden(NodoVehiculo nodo, DefaultTableModel modelo) {
        if (nodo != null) {
            recorrerInorden(nodo.izquierdo, modelo);
            agregarAFila(nodo.vehiculo, modelo);
            recorrerInorden(nodo.derecho, modelo);
        }
    }

    private void recorrerPreorden(NodoVehiculo nodo, DefaultTableModel modelo) {
        if (nodo != null) {
            agregarAFila(nodo.vehiculo, modelo);
            recorrerPreorden(nodo.izquierdo, modelo);
            recorrerPreorden(nodo.derecho, modelo);
        }
    }

    private void recorrerPostorden(NodoVehiculo nodo, DefaultTableModel modelo) {
        if (nodo != null) {
            recorrerPostorden(nodo.izquierdo, modelo);
            recorrerPostorden(nodo.derecho, modelo);
            agregarAFila(nodo.vehiculo, modelo);
        }
    }

 
  
    private void agregarAFila(Vehiculo v, DefaultTableModel modelo) {
        modelo.addRow(new Object[]{
            v.getPlaca(),
            v.getMarca(),
            v.getModelo(),
            v.getAnio(),
            v.getMultas(),
            v.getTraspasos(),
            v.getPropietario(),
            v.getDpi()
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHistorialMultas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVehiculos = new javax.swing.JTable();
        AgregarVehiculo = new javax.swing.JButton();
        ModificarVehiculo = new javax.swing.JButton();
        EliminarVehiculo = new javax.swing.JButton();
        VolverVehiculo = new javax.swing.JButton();
        PostOrden = new javax.swing.JButton();
        PreOrden = new javax.swing.JButton();
        Inorden = new javax.swing.JButton();

        PanelHistorialMultas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Historial de Vehiculos");

        jTableVehiculos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTableVehiculos.setForeground(new java.awt.Color(52, 152, 219));
        jTableVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Placa", "DPI/CUI", "Nombre", "Marca", "Modelo", "Año", "Multas", "Traspaso"
            }
        ));
        jTableVehiculos.setToolTipText("");
        jTableVehiculos.setGridColor(new java.awt.Color(0, 0, 0));
        jTableVehiculos.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jTableVehiculos);

        AgregarVehiculo.setBackground(new java.awt.Color(52, 152, 219));
        AgregarVehiculo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AgregarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        AgregarVehiculo.setText("Agregar Vehiculo");
        AgregarVehiculo.setFocusPainted(false);
        AgregarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarVehiculoActionPerformed(evt);
            }
        });

        ModificarVehiculo.setBackground(new java.awt.Color(52, 152, 219));
        ModificarVehiculo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ModificarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        ModificarVehiculo.setText("Modificar");
        ModificarVehiculo.setFocusPainted(false);
        ModificarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarVehiculoActionPerformed(evt);
            }
        });

        EliminarVehiculo.setBackground(new java.awt.Color(52, 152, 219));
        EliminarVehiculo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        EliminarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        EliminarVehiculo.setText("Eliminar");
        EliminarVehiculo.setFocusPainted(false);
        EliminarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarVehiculoActionPerformed(evt);
            }
        });

        VolverVehiculo.setBackground(new java.awt.Color(52, 152, 219));
        VolverVehiculo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        VolverVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        VolverVehiculo.setText("Volver");
        VolverVehiculo.setFocusPainted(false);
        VolverVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverVehiculoActionPerformed(evt);
            }
        });

        PostOrden.setBackground(new java.awt.Color(51, 153, 255));
        PostOrden.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        PostOrden.setForeground(new java.awt.Color(255, 255, 255));
        PostOrden.setText("Post Orden");
        PostOrden.setFocusPainted(false);
        PostOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostOrdenActionPerformed(evt);
            }
        });

        PreOrden.setBackground(new java.awt.Color(51, 153, 255));
        PreOrden.setForeground(new java.awt.Color(255, 255, 255));
        PreOrden.setText("Pre Orden");
        PreOrden.setFocusPainted(false);
        PreOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreOrdenActionPerformed(evt);
            }
        });

        Inorden.setBackground(new java.awt.Color(51, 153, 255));
        Inorden.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Inorden.setForeground(new java.awt.Color(255, 255, 255));
        Inorden.setText("Inorden");
        Inorden.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Inorden.setFocusPainted(false);
        Inorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InordenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelHistorialMultasLayout = new javax.swing.GroupLayout(PanelHistorialMultas);
        PanelHistorialMultas.setLayout(PanelHistorialMultasLayout);
        PanelHistorialMultasLayout.setHorizontalGroup(
            PanelHistorialMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHistorialMultasLayout.createSequentialGroup()
                .addGroup(PanelHistorialMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelHistorialMultasLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelHistorialMultasLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(AgregarVehiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModificarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EliminarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VolverVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelHistorialMultasLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(PanelHistorialMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelHistorialMultasLayout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(PreOrden)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PostOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Inorden, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        PanelHistorialMultasLayout.setVerticalGroup(
            PanelHistorialMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHistorialMultasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(PanelHistorialMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelHistorialMultasLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(PreOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelHistorialMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Inorden, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PostOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelHistorialMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VolverVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHistorialMultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHistorialMultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarVehiculoActionPerformed

    private void EliminarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarVehiculoActionPerformed
     int filaSeleccionada = jTableVehiculos.getSelectedRow();

    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un vehículo para eliminar.");
        return;
    }

    String placa = jTableVehiculos.getValueAt(filaSeleccionada, 0).toString(); // columna 0 = placa

    int confirmacion = JOptionPane.showConfirmDialog(this, "¿Eliminar vehículo con placa: " + placa + "?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

    if (confirmacion != JOptionPane.YES_OPTION) {
        return;
    }

    // Eliminar del árbol
    ArbolVehiculos arbol = GestorDatosGlobal.getVehiculos();
    boolean eliminado = arbol.eliminar(placa);

    if (eliminado) {
        // Recargar la tabla
        TablaVehiculos tabla = new TablaVehiculos();
        tabla.cargarInordenEnTabla(jTableVehiculos);
        JOptionPane.showMessageDialog(this, "Vehículo eliminado correctamente.");
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo eliminar el vehículo.");
    }
    }//GEN-LAST:event_EliminarVehiculoActionPerformed

    private void VolverVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverVehiculoActionPerformed
     
    }//GEN-LAST:event_VolverVehiculoActionPerformed

    private void InordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InordenActionPerformed
       cargarInordenEnTabla(jTableVehiculos);
    }//GEN-LAST:event_InordenActionPerformed

    private void PostOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostOrdenActionPerformed
       cargarPostordenEnTabla(jTableVehiculos);
    }//GEN-LAST:event_PostOrdenActionPerformed

    private void PreOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreOrdenActionPerformed
       cargarPreordenEnTabla(jTableVehiculos);
    }//GEN-LAST:event_PreOrdenActionPerformed

    private void ModificarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarVehiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarVehiculo;
    private javax.swing.JButton EliminarVehiculo;
    private javax.swing.JButton Inorden;
    private javax.swing.JButton ModificarVehiculo;
    private javax.swing.JPanel PanelHistorialMultas;
    private javax.swing.JButton PostOrden;
    private javax.swing.JButton PreOrden;
    private javax.swing.JButton VolverVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVehiculos;
    // End of variables declaration//GEN-END:variables
}
