/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectinifinal;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author josue
 */
public class TraspasoV extends javax.swing.JFrame {
     NuevoTrapasoPanel traspaso;
   private ListaCircularTraspasos Lista;


    /**
     * Creates new form TraspasoV
     */
    public TraspasoV() {
        initComponents();
   traspaso = new NuevoTrapasoPanel(this);
     agregarPlaceholder(jTextField1,"P123ABC");
     JTableHeader header = jTableTrapaso.getTableHeader();
header.setBackground(new Color(52, 152, 219));
header.setForeground(Color.WHITE); 
header.setFont(new Font("Segoe UI", Font.BOLD, 14));
this. Lista = GestorDatosGlobal.getTraspasos(); // Aquí se obtiene la lista
cargarTraspasosEnTabla();
    }
public JPanel getTraspasoV(){
return GestionarTraspasosPanel;
}
 private void agregarPlaceholder(JTextField campo, String textoPlaceholder) {
    campo.setForeground(Color.GRAY);
    campo.setText(textoPlaceholder);

    campo.addFocusListener(new FocusAdapter() {
        @Override
        public void focusGained(FocusEvent e) {
            if (campo.getText().equals(textoPlaceholder)) {
                campo.setText("");
                campo.setForeground(Color.BLACK);
            }
        }

        @Override
        public void focusLost(FocusEvent e) {
            if (campo.getText().isEmpty()) {
                campo.setForeground(Color.GRAY);
                campo.setText(textoPlaceholder);
            }
        }
    });
}
 public void Paneles (JPanel a){
    a.setSize(974,547);
    a.setLocation(0,0);
    GestionarTraspasosPanel.removeAll();
    GestionarTraspasosPanel.add(a,BorderLayout.CENTER);
    GestionarTraspasosPanel.revalidate();
    GestionarTraspasosPanel.repaint();
}
public void Panelprincipal(JPanel a){
    GestionarTraspasosPanel.add(a,BorderLayout.CENTER);
    GestionarTraspasosPanel.revalidate();
    GestionarTraspasosPanel.repaint();
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GestionarTraspasosPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        NuevoTraspaso = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTrapaso = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GestionarTraspasosPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Buscar por Placa");

        jTextField1.setText("jTextField1");

        Buscar.setBackground(new java.awt.Color(52, 152, 219));
        Buscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Buscar.setForeground(new java.awt.Color(255, 255, 255));
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        NuevoTraspaso.setBackground(new java.awt.Color(52, 152, 219));
        NuevoTraspaso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        NuevoTraspaso.setForeground(new java.awt.Color(255, 255, 255));
        NuevoTraspaso.setText("Nuevo Traspaso");
        NuevoTraspaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoTraspasoActionPerformed(evt);
            }
        });

        Modificar.setBackground(new java.awt.Color(52, 152, 219));
        Modificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Modificar.setForeground(new java.awt.Color(255, 255, 255));
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Eliminar.setBackground(new java.awt.Color(255, 0, 0));
        Eliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setText("Eliminar");

        jTableTrapaso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Placa", "DPI Anterior Dueno", "Nombre Anterior", "Fecha", "DPI Nuevo", "Nombre Nuevo"
            }
        ));
        jScrollPane1.setViewportView(jTableTrapaso);

        jLabel2.setText("Historial de Traspasos");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("=== DETALLES DEL TRASPASO SELECCIONADO ===\n\nNúmero de Transacción: TR1705847291234\nFecha del Traspaso: 15 de enero de 2024\nPlaca del Vehículo: P123ABC\n\nPROPIETARIO ANTERIOR:\nNombre: Juan Pérez García\nDPI: 2958927141001\nDepartamento: Guatemala\n\nPROPIETARIO NUEVO:\nNombre: María López Hernández\nDPI: 3045612789234\nDepartamento: Guatemala\n\nDETALLES DEL TRASPASO:\nMotivo: Venta del vehículo\nValor de la Transacción: Q25,000.00\nEstado: Completado\nOficina Registral: Guatemala Centro");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout GestionarTraspasosPanelLayout = new javax.swing.GroupLayout(GestionarTraspasosPanel);
        GestionarTraspasosPanel.setLayout(GestionarTraspasosPanelLayout);
        GestionarTraspasosPanelLayout.setHorizontalGroup(
            GestionarTraspasosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestionarTraspasosPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(GestionarTraspasosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
                    .addGroup(GestionarTraspasosPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(NuevoTraspaso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eliminar))
                    .addGroup(GestionarTraspasosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buscar))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        GestionarTraspasosPanelLayout.setVerticalGroup(
            GestionarTraspasosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestionarTraspasosPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(GestionarTraspasosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar))
                .addGap(18, 18, 18)
                .addGroup(GestionarTraspasosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar)
                    .addComponent(Modificar)
                    .addComponent(NuevoTraspaso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GestionarTraspasosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GestionarTraspasosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarActionPerformed

    private void NuevoTraspasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoTraspasoActionPerformed
   
    Paneles(traspaso.getnuevotraspasopanel());
    }//GEN-LAST:event_NuevoTraspasoActionPerformed
 public void cargarTraspasosEnTabla() {
    DefaultTableModel modelo = (DefaultTableModel) jTableTrapaso.getModel();
    modelo.setRowCount(0); // Limpiar tabla antes de llenar

    ListaCircularTraspasos.NodoTraspaso actual = Lista.getCabeza();
    if (actual == null) return;

    do {
        Traspaso t = actual.traspaso;
        Object[] fila = {
            t.getPlaca(),
            t.getDPI(),
            t.getPropietarioAnterior(),
            t.getFecha(),
            t.getNuevoPropietario(),
            t.getDepartamento()
        };
        modelo.addRow(fila);
        actual = actual.siguiente;
    } while (actual != Lista.getCabeza());
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraspasoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraspasoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraspasoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraspasoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraspasoV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JPanel GestionarTraspasosPanel;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton NuevoTraspaso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTrapaso;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
