/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectinifinal;
import com.mycompany.proyectinifinal.GraphvizGenerator;
import guru.nidi.graphviz.engine.Format;
import guru.nidi.graphviz.engine.Graphviz;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author josue
 */
public class VerEstructurasGrapiz extends javax.swing.JPanel {
private ArbolVehiculos arbolVehiculos;
    private ArbolAVL arbolAVL;
    private ListaDobleMultas listaMultas;
    private ListaCircularTraspasos listasTraspasos;
    /**
     * Creates new form VerEstructurasGrapiz
     */
    public VerEstructurasGrapiz() {
        initComponents();
        initListeners();
    }
private void initListeners() {
        MostrarABB.addActionListener(e -> mostrarDOT(GraphvizGenerator.generarABB(arbolVehiculos)));
        MostrarAVL.addActionListener(e -> mostrarDOT(GraphvizGenerator.generarAVL(arbolAVL)));
        MostrarListaDoble.addActionListener(e -> mostrarDOT(GraphvizGenerator.generarListaDoble(listaMultas)));
        MostrarListaCircular.addActionListener(e -> mostrarDOT(GraphvizGenerator.generarListaCircular(listasTraspasos)));
    }

 private void mostrarDOT(String dot) {
    try {
        BufferedImage image = Graphviz.fromString(dot)
                                     .render(Format.PNG)
                                     .toImage();
        JLabel label = new JLabel(new ImageIcon(image));
        label.setBounds(10, 10, image.getWidth(), image.getHeight());

        jPanel2.removeAll();
        jPanel2.add(label);
        jPanel2.revalidate();
        jPanel2.repaint();
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}

public JPanel getPanelGrapiz(){
return jPanel1;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MostrarABB = new javax.swing.JButton();
        MostrarAVL = new javax.swing.JButton();
        MostrarListaDoble = new javax.swing.JButton();
        MostrarListaCircular = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 839, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        MostrarABB.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        MostrarABB.setText("Mostrar ABB");
        MostrarABB.setFocusPainted(false);
        MostrarABB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarABBActionPerformed(evt);
            }
        });

        MostrarAVL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        MostrarAVL.setText("Mostrar AVL");
        MostrarAVL.setFocusPainted(false);
        MostrarAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarAVLActionPerformed(evt);
            }
        });

        MostrarListaDoble.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        MostrarListaDoble.setText("Mostrar Lista Doble");
        MostrarListaDoble.setFocusPainted(false);
        MostrarListaDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarListaDobleActionPerformed(evt);
            }
        });

        MostrarListaCircular.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        MostrarListaCircular.setText("Mostrar Lista Circular");
        MostrarListaCircular.setFocusPainted(false);
        MostrarListaCircular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarListaCircularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(MostrarABB)
                        .addGap(38, 38, 38)
                        .addComponent(MostrarAVL)
                        .addGap(62, 62, 62)
                        .addComponent(MostrarListaDoble)
                        .addGap(43, 43, 43)
                        .addComponent(MostrarListaCircular))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MostrarAVL)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MostrarListaDoble)
                        .addComponent(MostrarListaCircular)
                        .addComponent(MostrarABB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarABBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarABBActionPerformed
      String dot = GraphvizGenerator.generarABB(arbolVehiculos);
    mostrarDOT(dot);
    }//GEN-LAST:event_MostrarABBActionPerformed

    private void MostrarAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarAVLActionPerformed
         String dot = GraphvizGenerator.generarAVL(arbolAVL);
    mostrarDOT(dot);
    }//GEN-LAST:event_MostrarAVLActionPerformed

    private void MostrarListaDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarListaDobleActionPerformed
        String dot = GraphvizGenerator.generarListaDoble(listaMultas);
    mostrarDOT(dot);

    }//GEN-LAST:event_MostrarListaDobleActionPerformed

    private void MostrarListaCircularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarListaCircularActionPerformed
        String dot = GraphvizGenerator.generarListaCircular(listasTraspasos);
    mostrarDOT(dot);
    }//GEN-LAST:event_MostrarListaCircularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MostrarABB;
    private javax.swing.JButton MostrarAVL;
    private javax.swing.JButton MostrarListaCircular;
    private javax.swing.JButton MostrarListaDoble;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
